### ISSUE TITLE
[Feature Request]option for theming popup und longpress

### ISSUE THREAD

**Issue by daywalk3r666** [rkkr/simple-keyboard#109]
can you add an option for theming popup und longpress key?it would be nice if this match the custom keyboard color.

[Screenshot_20190613-110340_Bromite](https://user-images.githubusercontent.com/15938117/59419308-eff17600-8dca-11e9-808c-3f912e36590a.png)

**Comment by rkkr** [comment]
That is currently not possible due to requirement of static resources in order to support hardware accelerated rendering. Few techniques exist to customize the color dynamically, but that is not supported by some phones (like Samsung).

If someone can find an alternate solution, a pull request is welcome. This feature even existed in version 1.9, but was reverted in https://github.com/rkkr/simple-keyboard/commit/532ea2b5bc9909e90995efc95afb48d720aee575 .
