### ISSUE TITLE
[Request] Separate APKs for language dictionaries

### ISSUE THREAD

**Issue by smnthermes** [rkkr/simple-keyboard#126]
If the language dictionaries were implemented as separate APKs, the app wouldn't be bloated and wouldn't need internet access.

**Comment by jwsp1** [comment]
Unfortunately, it seems that the dev doesn't want dictonaries. 
There are a lot of closed issues regarding this topic, check them for dev's reasons

**Comment by Wilker-a** [comment]
to keep it short, the dev wants to keep the apk size...short.

**Comment by moriel5** [comment]
Can someone please explain to how support for external dictionaries, implemented via separate APKs, will somehow bloat  `Simple Keyboard` to the point that it will weigh more than 1MB?

**Comment by jwsp1** [comment]
@moriel5 you can use AnySoftKeyboard when you need language dictionaties. Thats what I'm suggesting to my friends as well.

**Comment by moriel5** [comment]
@rkkr I'm sorry but this just confuses me more, since I had thought that the reason this isn't being implemented is size.

@jwsp1 I'm an old-timer when it comes to AnySoftKeyboard (I had first used it on an Android 2.0 tablet around a decade ago), so I know all about it, however I stopped using it since I use some of GBoard's extra features (I'm on an old version that I had debloated), so that won't help me currently, but thanks in any case.
