### ISSUE TITLE
Vertical padding in number row

### ISSUE THREAD

**Issue by chamfay** [rkkr/simple-keyboard#132]
Hi! 
Thanks, simple and straightforward app.
Can you increase vertical padding in number row like this [Image](https://i.ibb.co/B3qf0Z1/padding.png) ?

**Comment by rkkr** [comment]
If you enable secondary characters, then it looks like this:
![image](https://user-images.githubusercontent.com/3480123/64549040-897fe380-d338-11e9-9061-7d23ad4ef866.png)

The lack of secondary characters and long-press is the reason why that row doesn't need to be as tall as other rows.

A long time ago when I added this feature GBoard did the same (if I remember correctly). Now I looked that they use same height for number row. I prefer having smaller total keyboard height, but if people will start to vote that they want same height, it can be changed.

**Comment by Wilker-a** [comment]
if preference is the issue, i believe it should be an option ("same dimensions for all buttons" or something)...  
i believe that it might apply for the padding of the keys, too. (see #128)

**Comment by wittmane** [comment]
I did some prototyping on the standard layout (sw600dp/sw768dp have more space to work with, so I'm sure something can be figured out for those as well), and I think we can make the number row the same height as the other rows without increasing the size of the keyboard by removing some of the vertical gap and bottom padding. This would make it look more like Gboard, and it would better allow support for shift changing the keys (as suggested in #206) and adding long presses for alternate keys, also similar to Gboard.

For the portrait layout, instead of
![NumberRowPortraitOriginal](https://user-images.githubusercontent.com/16480765/103472081-8212f380-4d4e-11eb-8c8c-d5992001d067.png)
it could be
![NumberRowPortraitReducedGap](https://user-images.githubusercontent.com/16480765/103472085-93f49680-4d4e-11eb-8318-57489ae35a8c.png)
which is done simply by having the bottom padding match the top padding and reducing the vertical gap to match the horizontal gap (when the device is wider than about 2in, the keyboard's height is based on the width, so for the vast majority of cases, we can make these gaps match). This left the height of the keys the same as in the 4 row keyboard. In doing this, the height of the keyboard only needs to be about 9% larger than the 4 row keyboard (as opposed to the 10% that is currently used).

For the landscape layout, instead of
![NumberRowLandscapeOriginal](https://user-images.githubusercontent.com/16480765/103472192-42e5a200-4d50-11eb-8f2c-989c93801cf6.png)
it could be
![NumberRowLandscapeReducedGap](https://user-images.githubusercontent.com/16480765/103472195-4bd67380-4d50-11eb-85d0-7cae6e032868.png)
which is done similar to the other one. In this case the keyboard is height is based on the height of the device (in landscape orientation), so we can't make the horizontal and vertical gaps match, so instead I had the vertical gap match the horizontal gap from the portrait layout (if it works for that, it should be fine for this). Just reducing the gap like this resulted in the keyboard being about 20% larger than the 4 row keyboard, so I also reduced the height of the keys to match what is currently used for the 5 row keyboard instead of the 4 row keyboard, and that made the keyboard only about 9% larger than the 4 row keyboard.

@rkkr does this seem like a decent change? There might be a couple tricky parts to implementing it, so I want to make sure you're alright with this before I waste too much time trying to make the change.

**Comment by rkkr** [comment]
@wittmane my concern is 5 row and many column languages. Those layouts are very cramped. They don't have extra number row support, so it shouldn't be too bad. If it looks fine there (make sure to test), then this change is fine.

I'm not sure about the bottom padding decrease, but it's just a few pixels and can be easily changed back.

**Comment by wittmane** [comment]
@rkkr to clarify, I would be changing the vertical gap on all alphabet keyboards to match the horizontal gap from a 10 column keyboard (I'm basically using that as a benchmark for the minimum gap to use between keys), so in the case of keyboards with extra columns the horizontal and vertical gap wouldn't end up matching, but the vertical gap would be smaller than it currently is. Also, for keyboards that normally have 5 rows and don't support a separate number, I'd just make the same adjustments for them normally (reducing the vertical gap), so they would look the same as a 4 row keyboard with a separate number row. Hopefully that resolves the concerns you had.

Currently when the number row is enabled, the height of the keyboard is increased for all keyboards. This means that things like the number keyboard is also taller, which doesn't seem necessary. Based on how I'm thinking about making the change, I could increase the height only for the alphabet/symbols keyboards. That would also allow the 5 row keyboards to always get the extra height, even if the separate number row setting is off. Since you would need to change text fields to see the change in height of the keyboard, I don't think it will be a problem. That's how Gboard works. I don't feel too strongly about this, so if you would prefer that we keep all keyboards the same height, I can leave that how it is.

**Comment by rkkr** [comment]
Leave the dynamic height for a seperate PR and discussion. There is no support for runtime layout change so this would be a significant rendering code refactor. I'm also sceptical how input apps will react to a height change as in some cases they would need to either scroll or scale their layout.
