### ISSUE TITLE
Swipe action got forwarded to the container when beginning of the text reached

### ISSUE THREAD

**Issue by ilimat** [rkkr/simple-keyboard#147]
faced in Viber chat app. in a conversation. when writing text and swiping to the beginning of the text.

when the beggining is reached, the further move of the finger causes the entire screen to accept the swipe gesture and do the screen switch.

expected behaviour: when beginning of the text reached the swipe gesture is not causing the screen to move, only text cursor.

actual: screen got switched like if user does swipe gesture on the screen itself (or, maybe if they do left arrow click)

see sample on youtube video Oue-Jkj4-DQ

**Comment by rkkr** [comment]
If you are talking about the space swipe, then this "feature" is known. You can either ask the app to move the pointer to a specified index, or do a "left arrow key click" and let the OS handle it.

The first one is the nicer way (and it doesn't have this bug), but the problem is that some apps don't handle these indexes. Either the move doesn't work, or pointer jumps randomly in the screen.

The second one works across all apps. Unless the app tries to handle the left/right click in a weird way.

It is unlikely to be fixed as we would probably just swap one bug for the other.

**Comment by ilimat** [comment]
Yes, ok swipe delete is doing it another way. Could you please give a sample of the application with index problem? Is it some type of text editors with multy line?

**Comment by rkkr** [comment]
[38.apk.zip](https://github.com/rkkr/simple-keyboard/files/3827021/38.apk.zip)

This was in the beta version 2.13.

**Comment by rkkr** [comment]
Fallback added in 5c1e49598965ccaccaeb1ecd9b4a4ee6222d5eff and is in beta
