### ISSUE TITLE
Question: Launcher icon

### ISSUE THREAD

**Issue by jorgman1** [rkkr/simple-keyboard#156]
I've noticed that you removed the possibility to hide the launcher icon with the reason that it is an Android 10 policy.
Isn't there a possibility to leave the button in the preferences and make it opt-in instead of opt-out as before? Or is it completely prohibited in Android 10?

**Comment by rkkr** [comment]
In Android 10 if application has no active icon, then it adds a fake icon which opens the application info from the system settings (the one with Force Stop and Uninstall buttons). So there is no way to hide it. If you want to hide it, you should use a custom launcher like [Lawnchair](https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah) which has it's own list for icon hiding. Lanwchair also doesn't add this fake icon even in Android 10, but I won't bet on that in the long term.

I could add a check and still show this setting for <10, but I probably won't do that. The reason is because this requirement came due to malicious apps that try to hide after they are installed. It is likely Play Store will soon flag all apps that contain icon hiding code (even if that part of code isn't used).

**Comment by jorgman1** [comment]
Yeah, if the policy is going that way, then it probably doesn't make sense to have it somewhere in the code. That way it stays cleaner as well.
Thank you for the explanation, it makes much more sense now!

And happy new year!
