### ISSUE TITLE
An option to include more character formats and IPA characters as secondary characters

### ISSUE THREAD

**Issue by Wilker-a** [rkkr/simple-keyboard#158]
i miss having something similar on Microsoft's SwiftKey, although the characters there were just various accentuations. that said, it would be cool to have characters such as `ɪ` under the letter `e` or `i`, or `ð` under the letters `t` or `h`. probably as an opt-in function, at least. 

what do you think? :3

###### resource: [IPA chart](http://ipachart.com), [youtube video by Tom Scott explaining some of the chart](https://www.youtube.com/watch?v=9uZam0ubq-Y)

**Comment by rkkr** [comment]
Due to the static layouts making it an opt-in requires to duplicate the layout files and add switches on top. I wouldn't want to do that.

This leaves two options:
1. Adding them for all languages without an opt-out
2. Making a new layout where they would be primary characters

This depends on a use case. If you want to type whole words in these characters, having a separate layout makes sense. If you'll only type separate letters, then the first option makes sense.

I will not add this feature myself as I won't know has this would be used. A PR can still be made.
