### ISSUE TITLE
Hiding numbers

### ISSUE THREAD

**Issue by FLOSSly** [rkkr/simple-keyboard#224]
I want to hide the numbers (on the row of qwerty) with the enabling of "Hide special characters". Will you please think over it? 

The only reason is it seems distracting while typing and sometimes numbers are being typed mistakenly in place of letters.

**Comment by licaon-kter** [comment]
Isn't there a special toggle just for numbers?

**Comment by rkkr** [comment]
"Hide special characters" doesn't hide the extra numbers shown on top row. I don't intend to change that as this is the default layout used in AOSP. The "special toggle just for numbers" is "show extra numbers row".

Neither of them will solve your "numbers are being typed mistakenly in place of letters" problem. With special characters hidden, all keys still have extra characters accessible thru long-press. If I remove the numbers from that list, instead of mistakenly getting "7" when you long-clicked "u", you will get "ū", or whatever is the special character for your language. This also applies to all other keys not just the top row.

You can try increasing the "Key long press delay" in advanced settings. It won't be that sensitive to use special chars.
