### ISSUE TITLE
Aggressive capitalisation

### ISSUE THREAD

**Issue by JonnyTech** [rkkr/simple-keyboard#226]
Pre v4, input boxes for username and password do not capitalise the first character.

Post v4, input boxes for username and password do capitalise the first character.

Observed on Google mail and various other sites.

**Comment by rkkr** [comment]
Tetsed in https://accounts.google.com/ and I don't see what you described neither in email nor in password fields. There are also no capitalisation changes introduced in V4. There were capitalisation changes a few versions back, but only for recapitalisation.

**Comment by JonnyTech** [comment]
Hmm, maybe I skipped a version or two. But the isssue happens all the time for me. I may start uninstalling stuff to find the culprit. Maybe browser (firefox / fenix / iceraven) is the culprit..

**Comment by rkkr** [comment]
The input fields that have type "email" or "password" should never be capitalized. You can check that the email (username) field is properly detected if "@" is shown left to space key (instead of ","). You can also use https://play.google.com/store/apps/details?id=rkr.imetest to go thru all the input types and verify how they behave. This will rule out all the browser side.

If the magic still doesn't disappear, then specify your keyboard layout, phone + OS and exact browser + page (or app).

**Comment by JonnyTech** [comment]
Sorry, had missed your reply. The @ sign is shown but first letter capitalised:

![Screenshot_20210220-132335_Iceraven](https://user-images.githubusercontent.com/3584732/108596755-f3e6e100-737e-11eb-8947-ba1d902166bd.png)

Layout language English (UK), LineageOS 16.0 (also tried 17 and18), IceRaven browser (https://github.com/fork-maintainers/iceraven-browser/) - also tried other (Firefox based browsers. Downloaded from F-Droid as do not use Google Apps. Have not had a chance to try previous versions to confirm last one that worked correctly.

**Comment by rkkr** [comment]
This is a IceRaven browser bug. I'll check afterwards but I guess they specifically set such capitalization mode. All is good in Chrome world. As I remember I also checked Firefox and it worked fine there.
