### ISSUE TITLE
[Feature request] Make all colors customizable

### ISSUE THREAD

**Issue by SeerLite** [rkkr/simple-keyboard#229]
Hi!
I'd like to have a way to customize the foreground, space/return, and shift colors. Currently only the background color can be changed.

Thanks!

**Comment by rkkr** [comment]
It probably won't be possible to dynamically change all the colors/dimensions due to hardware rendering. They are drawn from static files. Background color is an exception as it is drawn on top of the static background. And making all things customizable will be hard to use in the settings.

My current plan is to see how [theme customization in Android 12](https://9to5google.com/2021/01/27/android-12-working-on-in-depth-theming-system-that-can-even-recolor-apps/) will work. Theoretically you would just set System Theme and then set how it looks in the System Settings.

**Comment by s99h** [comment]
Would it be possible to add an option to change the transparency of the background colour?

**Comment by rkkr** [comment]
@s99h background transparency should not be possible. As I remember Android blanks the area where keyboard is drawn. You would see a black background, not the app below. You could try to hack something using "draw over other apps", but all that are hacks. Many apps also resize to the remaining area above the screen, so you wouldn't see anything below.

**Comment by JM480** [comment]
Will this feature only be available on Android 12+?

**Comment by rkkr** [comment]
Yes, this would be a 12+ exclusive. Maybe I'll try to add it this weekend. I've stumbled upon this theming code in Lawnchair repo. They used an appcompat library, not the android API directly. Tutorials also do the same. So it may be more complicated than expected to access that color pallet.

**Comment by rkkr** [comment]
My fears were right. Material3 along with all the dynamic theming is not a part of Android SDK. Google has put it into a Maven package which inflates the keyboard size to 2.8MB when added (that's with proguard enabled).

The overridable colors are a part of Android SDK, and in a Pixel they can be manually overriden or pick the wallpaper color. Dark/Light switching and all the color mapping had to be done manually. The icons look strange (like enter key) as they are images and don't change the color. They could be replaced with unicode chars, but old Androids lack many of them.

This kind of works: https://github.com/rkkr/simple-keyboard/commit/0be1c1ad2e394c7fa0a75a509743a5f316407896

**Comment by JM480** [comment]
Has this feature been fully implemented yet?

**Comment by rkkr** [comment]
Dynamic theming is in v5.8
