### ISSUE TITLE
Changing to another keyboard instead of language

### ISSUE THREAD

**Issue by itskareem** [rkkr/simple-keyboard#255]
when i click on language change button it changed from simple keyboard to gboard or openboard instead of changing language

**Comment by rkkr** [comment]
This is by design. The Globe button switches to "next input method". That can be another language or another keyboard. If you long-press Globe or Space you will see the method list. It should always switch to the next one. If next language is in Simple Keyboard, then it will change the language within Simple Keyboard.

GBoard stopped using operating system input methods (OS doesn't see what languages keyboard has) and removed the switching to languages outside GBoard to lock you in. This is not Android compliant.
Looks like OpenBoard also copied this change, but Globe key is hidden by default. I still think this is wrong.
