### ISSUE TITLE
Edit Selection - both ways

### ISSUE THREAD

**Issue by yashpalgoyal1304** [rkkr/simple-keyboard#321]
### Steps:
make a selection > swipe across space

### Reality:
the selection is edited (which's nice), but only one side of it

### Suggestion:
some way to edit both sides of selection would be very good to increase efficiency

### Details:
* i think one way can be that the space bar splits in 2 when there's a selection. dragging on the right part will edit right side of selection, and dragging on left will edit left side.
* this can be made optional

duplicate 🔍 : [edit selection](https://github.com/rkkr/simple-keyboard/issues?q=is%3Aissue+is%3Aopen+edit+selection)

**Comment by rkkr** [comment]
Dividing spacebar into two is not an option, this will confuse people. 

An alternate idea would be using multiple touch points: put two fingers on space and right side selection moves right side, left on moves the left one. The problem is that there's only a single touch point being reported inside the application. Can't tell if it's just only one used, or there's some limitation for input methods service. This would also be non-obvious and not very usable for layouts that have many buttons in the bottom row and a small spacebar key.

There was a similar bug/comment for the delete swipe somewhere. Deletion selection is possible in both directions thru such bug/feature which I never fixed:
- Swipe left to select some text
- Keep backspace pressed
- Swipe space to modify right side selection
- Release backspace to commit deletion
It's possible to add a check for reverse release order (currently whenever you release backspace it deletes), but that is too risky. You mess up your order and all the text is gone instead of selection.

**Comment by yashpalgoyal1304** [comment]
1. i agree that dividing spacebar will confuse ppl if it's on by default,   
however, it will not if they stumbled upon it and decide to turn it on themselves (that's how i found out about space and bkspc swipe gestures in the first place :wink:)

2. yeah, i agree that the layouts with small spacebar key dont have much viable options in this direction of solution

3. yeah, this method will be veryyyyy wonky and will have extremely low chance of going mainstream. and i will be hesitant to use that method too 😅 



amh, except for small spacebar layouts, i still think that two space keys will be a good solution **when implemented as a choice, and OFF by default** - because by that way, it will be shown only to those users who already want to behave it that way

**Comment by yashpalgoyal1304** [comment]
hey, so, rather than splitting the spacebar how about giving an extra single button instead?? 

* function of the key: toggle which side of the selection will be edited
* location of the key: any side of spacebar
<img src="https://user-images.githubusercontent.com/19423063/143518953-18a7c1db-751b-4e51-b438-6667d7e2c8ee.png" height="160px">

For example, if the current side being edited on the action (of swiping on spacebar) is left, then tapping that key will make the selection's right side to be edited on action.

Thoughts??

**Comment by Erifxof** [comment]
Clavier ne s'affiche pas

**Comment by licaon-kter** [comment]
@Erifxof did you just respond to a random issue?

The keyboard can be enabled in Android Settings - System - Input?

**Comment by goyalyashpal** [comment]
> * function of the key: toggle which side of the selection will be edited

this is also called as "flip selection cursor" in modal text editors for desktop (kakoune, helix, vim, etc)

and i just very recently found an extension to provide exact this capability on vs codium/code as well 😃 : `alt - i`: https://github.com/mlewand/vscode-selection-flip/issues/3

**Comment by goyalyashpal** [comment]
* i so wish this & delete button (#228 ) made its way in in rkkr/simplekeb :sigh
