### ISSUE TITLE
Emoji and clipboard

### ISSUE THREAD

**Issue by Smile85363** [rkkr/simple-keyboard#394]
I think it's worth adding these two most important functions to Simple Keyboard

**Comment by snipe2004** [comment]
I must say this is the last blocking point for me about SimpleKeyboard.
I have no idea why it would be difficult, but a button (like Swiftkey) or a bar (like Youtube) wiuod do the job perfectly, just calling and displaying the list of emojis...

![Screenshot_20230517-133807](https://github.com/rkkr/simple-keyboard/assets/3645827/cecbb005-3330-41df-92bc-de46d121cb00)

Please tell us if we can ease the process of this implementation. Nowadays, not being able to input smileys/emojis is socially difficult, most people find me rude since I switched to Simple Keyboard ;)

**Comment by Justauser0** [comment]
It would be a great feature

**Comment by rkkr** [comment]
dup
