### ISSUE TITLE
delete key in Pocket-App does not work

### ISSUE THREAD

**Issue by matth-u** [rkkr/simple-keyboard#449]
When entering tags in the Pocket app (bookmark app from Mozilla), the delete key does not work with Simple Keyboard. This error only occurs with this keyboard, not with others. If this can be fixed, it would be great!  The keyboard is otherwise very helpful .
Thank you very much!
matth-u

**Comment by rkkr** [comment]
Delete swipe or just delete click?

**Comment by matth-u** [comment]
Delete by clicking. I don't use the delete by wiping function at all (I don't even know how to do it....).
Thank you.

**Comment by rkkr** [comment]
File a bug to Mozilla. I've connected a bluetooth keyboard and not only Delete key doesn't work but also input field looses focus after entering any single character. That Pocket app is just horrible.

The difference between keyboard apps comes from two ways a character can be deleted. Either you can send a Backspace click event (like a physical keyboard which is a more generic way) and let the OS and app handle the deletion, or you can take the input text of a field and cursor location, remove a char before cursor, update the input text and move the cursor. The latter option doesn't work on apps that don't provide cursor location or input manipulation capabilities. Originally Simple Keyboard checked if app provides all these functions and used them instead of plain keyboard clicks which broke apps that say that they support these operations, but always return 0 cursor location and "" texts.
