### ISSUE TITLE
Korean keyboard needed <한국어 키보드>

### ISSUE THREAD

**Issue by SunWithIssues** [rkkr/simple-keyboard#460]
There should be a korean keyboard. The capital letter key should have similar structure as what the branah site's shift key.

https://www.branah.com/korean

**Comment by rkkr** [comment]
Character composition input is not possible because this is a fork of LatinIME.

**Comment by SunWithIssues** [comment]
Hmm, the Arabic keyboard layout does character composition though. Can you leave this open and say that I am working on it?

**Comment by wittmane** [comment]
I'm not very familiar with Arabic, but I'm fairly certain simple keyboard currently doesn't support combining characters like Korean. I think what you're seeing is just ligatures.

I've already been working on adding support for Korean, so if you haven't already started, you don't need to. I've been working on a related issue that I got distracted on that is helpful to address, but I can make Korean work without it. I haven't been in much of a rush since no one else was asking for it (and I have it working on my device), but I can move back to focus on that if you're eager for it so we don't duplicate work. What I have is fully functional, but I still need to do some cleanup.

**Comment by rkkr** [comment]
I personally won't be working on adding Korean support. You are welcome to make PRs, but it will be hard to add without breaking existing functionality and without UI hacks. And PRs with hacks are not likely to be merged.

**Comment by SunWithIssues** [comment]
>What I have is fully functional, but I still need to do some cleanup.

@wittmane 

I definitely don't want to repeat work, if you already have a functional version. If you have a semi-working branch, I'd be happy to just bundle it locally to my phone. Korean is the only keyboard where I am still using Gboard.

**Comment by wittmane** [comment]
@SunWithIssues, I need to straighten out a few things before pushing a branch, but I can try to get that up in the next few days for you to work with before I'm ready to submit the PR.

**Comment by wittmane** [comment]
@SunWithIssues, I pushed my branch: https://github.com/wittmane/simple-keyboard/tree/korean_support
Let me know if you find any bugs or have suggestions to improve it.

**Comment by rkkr** [comment]
- Doesn't work on Android 4.4: blanks in place of all composed characters and blank language name on spacebar.
- You had to bring back the text composition logic for character composition. It was removed along with autocorrection.
- Raw inputs like SSH in ConnectBot are not handled.

For these reasons I wouldn't want to complicate this project.

**Comment by wittmane** [comment]
The issue with Android 4.4 seems to be a font issue. I replaced the font in `/system/fonts/DroidSansFallback.ttf` in my emulator, and it works fine. I have an old device running Android 4.1, and it doesn't have an issue displaying these characters, so I don't think Android 4.4 simply doesn't support it (maybe just an issue with the emulator or the specific fonts shipped with some devices). That emulator had the same issue with displaying Bengali characters (and possibly others that I didn't check), so unless you want to remove support for that because of this, this alone shouldn't be a good reason to not add support for Korean. Also, since the subtypes are managed virtually, I think it would be simple enough to disable specific languages on specific Android versions if that's necessary.

I did have to bring back text composition logic, but I don't see how that's a problem. If you're concerned that composition would only be relevant for Korean, I don't think that's necessarily the case. I know that there are other languages that use dead keys, such as Vietnamese (which Gboard has handling for), that could benefit from being able to compose text.

I did add handling for `InputType.TYPE_NULL` (which is what I assume you're referring to as "raw inputs"), but ConnectBot [specifies some input type variations/flags along with TYPE_NULL](https://github.com/connectbot/connectbot/blob/main/app/src/main/java/org/connectbot/TerminalView.java#L544), which as far as I understand things is inappropriate. Still, I updated handling to just look at the class for handling `TYPE_NULL` to be able to manage this sort of behavior gracefully. The framework EditText has some weird handling for `TYPE_NULL` to track an invisible composition that only gets added to the field when finishing the composition (which might actually be more of a bug than an intended feature). That might be somewhat reasonable for an IME with a suggestion bar to at least show the composed text, but it seems very confusing without that. Also, nothing actually stops a custom editor from more fully supporting composing text or allowing moving the cursor around without informing the IME, and documentation for that type doesn't seem clear enough to me to know what behavior should just be considered as an editor misbehaving. All of this makes the functionality of this type unpredictable related to composing, so I decided to just disable composition in this case. Gboard similarly doesn't support composing text in these text fields and forces a qwerty keyboard. It seemed odd to change the layout, so I just left the layout and only disabled composing, but I'd be fine changing it to match Gboard.

Even though adding composing adds a bit more complexity to the project, I think this amount is still worth it to support additional languages so people don't need separate apps for different languages, which is presumably why Google merged functionality from LatinIME and Google Korean Input into one app (Gboard). I hope you'll reconsider your stance on this.
