### ISSUE TITLE
73 MB used RAM constantly

### ISSUE THREAD

**Issue by RiQuY** [rkkr/simple-keyboard#52]
I don't know if this is an error but I think is not pretty normal that everytime I check the RAM usage the keyboard is always using 73 MB, any messaging app (23 MB) or browser uses less RAM.
Any explanation?

My smarthpone is a Xiaomi Redmi Note 4 X, with Android 7.0 NDR90M (MIUI 9.6.2.0) with 3.0GB RAM.

**Comment by rkkr** [comment]
In my 4.4 tablet it uses 5,4mb. In 8.1 phone it uses 15mb. 73 looks weird, but it all depends in cashing,  as OS might try to preload all 50 languages and 4 themes. And shared resources can be included or excluded. Anyways I can't tell anything without a process dump. Also average usage is shown by default, which will lover it for apps like browser which you don't use all the time. Chrome uses 1,4gb in my phone.

**Comment by RiQuY** [comment]
There you have a screenshot, idk this can be useful to you. I checked If I was RAM or disk space/cache, and it is RAM.
https://cdn.discordapp.com/attachments/428542615906942986/490219719903674369/Screenshot_2018-09-14-19-56-41-974_com.miui.cleanmaster.png

**Comment by rkkr** [comment]
A screenshot is not a memory dump. It doesn't help in any way.

**Comment by RiQuY** [comment]
If you tell me how to do that I will share it with you.

**Comment by rkkr** [comment]
Option 2 in
https://dzone.com/articles/how-to-capture-heap-dump-from-android-app

**Comment by RiQuY** [comment]
Well, here we go, Heap Dump of about one minute, and the allocation too (I think I recorded bad the alloc file).

As you can see in the Heap Dump, the keyboard uses about 20/30MB when it is running on background, but if you open some app and type, obviusly the app will load the graphics for the keyboard which adds 20/30MB.
Until now I think this is normal behavior but the weird part is this:
Even if you close the app where you were writing the graphic memory for the keyboard will be still loaded so now, the process in the background is 50/60MB in memory, instead the 20/30MB it should be, because the graphic memory is still loaded.
To free the graphics memory of the keyboard I need to go to my RAM cleaner app and run it, to have again the normal keyboard process using 20/30MB when in background.

You can check this on the heap file I attached, when you see the jumps in the memory is because I'm opening apps to write or using the RAM cleaning app to free the graphic memory.
I ran these test with my smarthpone is a Xiaomi Redmi Note 4 X, with Android 7.0 NDR90M (MIUI 9.6.2.0) with 3.0GB RAM, as mentioned on the original post.

[simple-keyboard-49.zip](https://github.com/rkkr/simple-keyboard/files/2534383/simple-keyboard-49.zip)

I hope this helps, please reopen the issue.

**Comment by rkkr** [comment]
You should never need to "clean RAM". Android does a good job of cashing and suspending background apps. It is logical that graphic memory is not freed up when app minimizes, as this is managed by OS and it keeps it in memory in case you'll open it again. It will only do that if it will start running out of memory.

My phone probably frees the graphic memory as usage is ~50MB when typing, but average is ~15MB in background. That might be because your phone has +1GB of RAM and it can cache more. I'll check what's in the dump.

**Comment by RiQuY** [comment]
@rkkr Any news?

**Comment by rkkr** [comment]
The attached dump only has 30MB memory usage. It might be made at the time when it was lower. I've looked at memory usage a year ago, and then there wasn't anything wrong in it.

Attached dump:
![image](https://user-images.githubusercontent.com/3480123/48149388-98cf7400-e2c4-11e8-91bc-088f1c505813.png)

"Retained Size" shows the total memory usage of these objects including all their references. Everything that this keyboard explicitly consumes is ~1.2MB. There are lots of other things that were used to start this application and provide resources to it obviously.

![image](https://user-images.githubusercontent.com/3480123/48149998-2790c080-e2c6-11e8-8188-a0bfcb86ae59.png)

The top item in the dump with 32MB is FinalizerReference. https://stackoverflow.com/questions/35755589/memory-usage-analysis-using-android-studio . It should mean "all objects that use finalizing and are not recycled because they are still in use, or OS just hasn't run the garbage collection yet". As written all over the internet there isn't much an app can do to control it. Except not use android SDK which is not an option.

The second place with 2MB is byte[]. This includes many resources like keyboard bitmaps, xml configuration files, etc. And strange things like Dalvik cache.
The third place with 743KB is char[]. These are mostly key texts and layouts for all languages.

So everything is still normal so far. If OS doesn't recycle this memory, then this is how it decides is best to optimize the app opening and conserve the battery as recycling memory requires CPU resources. Nexus 5X recycles the memory from ~50MB to ~15MB when keyboard is minimized. Xiaomi thinks it's better to keep everything in memory.
